"""NSE mid-cap and small-cap universe for intraday screening.

A representative list of liquid mid/small-cap stocks traded on NSE.
All tickers use the .NS suffix for yfinance compatibility.
"""

NSE_MIDCAP_SMALLCAP_UNIVERSE = [
    # Mid-cap 150 representative
    "AARTIIND.NS", "ABBOTINDIA.NS", "ABCAPITAL.NS", "ABFRL.NS", "ADANIGREEN.NS",
    "ADANIPOWER.NS", "ADANITRANS.NS", "AJANTPHARM.NS", "ALKEM.NS", "AMBUJACEM.NS",
    "APOLLOHOSP.NS", "APOLLOTYRE.NS", "ASHOKLEY.NS", "ASTRAL.NS", "ATGL.NS",
    "AUBANK.NS", "AUROPHARMA.NS", "BAJAJHLDNG.NS", "BALKRISIND.NS", "BANDHANBNK.NS",
    "BANKINDIA.NS", "BATAINDIA.NS", "BEL.NS", "BERGEPAINT.NS", "BHARATFORG.NS",
    "BHEL.NS", "BIOCON.NS", "BLUEDART.NS", "BPCL.NS", "BSOFT.NS",
    "CANBK.NS", "CGPOWER.NS", "CHOLAFIN.NS", "CIPLA.NS", "COFORGE.NS",
    "COLPAL.NS", "CONCOR.NS", "COROMANDEL.NS", "CROMPTON.NS", "CUB.NS",
    "DABUR.NS", "DALBHARAT.NS", "DEEPAKNTR.NS", "DELHIVERY.NS", "DIVISLAB.NS",
    "DIXON.NS", "DLF.NS", "DRREDDY.NS", "EICHERMOT.NS", "ESCORTS.NS",
    "EXIDEIND.NS", "FEDERALBNK.NS", "GAIL.NS", "GMRINFRA.NS", "GODREJCP.NS",
    "GODREJIND.NS", "GODREJPROP.NS", "GRANULES.NS", "GRASIM.NS", "GUJGASLTD.NS",
    "HAL.NS", "HAVELLS.NS", "HCLTECH.NS", "HDFCAMC.NS", "HDFCLIFE.NS",
    "HINDPETRO.NS", "HINDZINC.NS", "ICICIGI.NS", "ICICIPRULI.NS", "IDEA.NS",
    "IDFCFIRSTB.NS", "INDHOTEL.NS", "INDIAMART.NS", "INDIGO.NS", "INDUSINDBK.NS",
    "INTELLECT.NS", "IPCALAB.NS", "IRCTC.NS", "JINDALSTEL.NS", "JKCEMENT.NS",
    "JUBLFOOD.NS", "KOTAKBANK.NS", "L&TFH.NS", "LAURUSLABS.NS", "LICHSGFIN.NS",
    "LTIM.NS", "LTTS.NS", "M&MFIN.NS", "MANAPPURAM.NS", "MARICO.NS",
    "MCDOWELL-N.NS", "METROPOLIS.NS", "MFSL.NS", "MGL.NS", "MINDTREE.NS",
    "MOTHERSON.NS", "MPHASIS.NS", "MRF.NS", "MUTHOOTFIN.NS", "NATIONALUM.NS",
    "NAUKRI.NS", "NAVINFLUOR.NS", "NESTLEIND.NS", "NMDC.NS", "OBEROIRLTY.NS",
    "OFSS.NS", "PAGEIND.NS", "PEL.NS", "PERSISTENT.NS", "PETRONET.NS",
    "PFIZER.NS", "PIIND.NS", "PNB.NS", "POLYCAB.NS", "POWERGRID.NS",
    "RBLBANK.NS", "RECLTD.NS", "SAIL.NS", "SBICARD.NS", "SBILIFE.NS",
    "SIEMENS.NS", "SRF.NS", "SUNPHARMA.NS", "SYNGENE.NS", "TATACOMM.NS",
    "TATAELXSI.NS", "TATAPOWER.NS", "TATATECH.NS", "TCS.NS", "TECHM.NS",
    "TIINDIA.NS", "TORNTPHARM.NS", "TORNTPOWER.NS", "TRENT.NS", "TVSMOTOR.NS",
    "UBL.NS", "ULTRACEMCO.NS", "UNIONBANK.NS", "UPL.NS", "VBL.NS",
    "VEDL.NS", "VOLTAS.NS", "WHIRLPOOL.NS", "WIPRO.NS", "YESBANK.NS",
    "ZEEL.NS", "ZOMATO.NS", "ZYDUSLIFE.NS",
    # Additional small-cap / high-volatility names
    "AWL.NS", "BSE.NS", "CDSL.NS", "CENTRALBK.NS", "CESC.NS",
    "CYIENT.NS", "EPL.NS", "FACT.NS", "FSL.NS", "GLENMARK.NS",
    "GSPL.NS", "HUDCO.NS", "IEX.NS", "IRFC.NS", "JBCHEPHARM.NS",
    "JSL.NS", "KALYANKJIL.NS", "KARURVYSYA.NS", "KEI.NS", "KNRCON.NS",
    "LAXMIMACH.NS", "MAHABANK.NS", "MAHLIFE.NS", "MASTEK.NS", "MAXHEALTH.NS",
    "MEDANTA.NS", "MOTILALOFS.NS", "NATCOPHARM.NS", "NCC.NS", "NH.NS",
    "OIL.NS", "PAYTM.NS", "POLICYBZR.NS", "RATNAMANI.NS", "RKFORGE.NS",
    "RVNL.NS", "SJVN.NS", "SONACOMS.NS", "SUZLON.NS", "TANLA.NS",
    "TATACHEM.NS", "TATACOFFEE.NS", "TATASTEEL.NS", "TRIDENT.NS", "VMART.NS",
]
